/* SPDX-FileCopyrightText: 2026 CyclesPlus
 *
 * SPDX-License-Identifier: Apache-2.0 */

/* === CyclesPlus: Personal Photon Profile Types Begin === */
#pragma once

#include "util/types.h"

CCL_NAMESPACE_BEGIN

/* Raw counts from 1/1024 hashed pixel/sample paths, not extrapolated totals.
 * Shards reduce contention; 64-bit counters are reset at each render_samples call. */
enum {
  PHOTON_PROFILE_SAMPLE_MASK = 1023,
  PHOTON_PROFILE_SHARDS = 64,
};

enum PhotonVolumeProfileCounter {
  PHOTON_PROFILE_HOMOGENEOUS_SEGMENTS,
  PHOTON_PROFILE_MARCH_SEGMENTS,
  PHOTON_PROFILE_ROOT_REJECTS,
  PHOTON_PROFILE_SHADER_SAMPLES,
  PHOTON_PROFILE_SHADER_EMPTY,
  PHOTON_PROFILE_CACHE_MISSES,
  PHOTON_PROFILE_NO_SCATTER_STEPS,
  PHOTON_PROFILE_PRE_BEAM_STEPS,
  PHOTON_PROFILE_ATTENUATION_EXITS,
  PHOTON_PROFILE_STEP_LIMITS,
  PHOTON_PROFILE_QUERIES,
  PHOTON_PROFILE_EMPTY_QUERIES,
  PHOTON_PROFILE_NODES,
  PHOTON_PROFILE_NODE_REJECTS,
  PHOTON_PROFILE_LEAVES,
  PHOTON_PROFILE_CANDIDATES,
  PHOTON_PROFILE_DEGENERATE_BEAMS,
  PHOTON_PROFILE_RADIAL_REJECTS,
  PHOTON_PROFILE_CAP_REJECTS,
  PHOTON_PROFILE_INTERVAL_REJECTS,
  PHOTON_PROFILE_HITS,
  PHOTON_PROFILE_HG_EVALS,
  PHOTON_PROFILE_CLOSURE_EVALS,
  PHOTON_PROFILE_STACK_OVERFLOWS,
  /* === CyclesPlus: Beam Integral Reuse Counter Begin === */
  PHOTON_PROFILE_INTEGRAL_REUSES,
  /* === CyclesPlus: Beam Integral Reuse Counter End === */
  PHOTON_PROFILE_NUM_COUNTERS,
};

CCL_NAMESPACE_END
/* === CyclesPlus: Personal Photon Profile Types End === */
